=== almost/Marvin-Jabber-Client/docs/skindef/skindef.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT skindef (description, (resource | message | textvariable | window)*)>
<!ATTLIST skindef
	name CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA)>
<!ELEMENT window (description, (area | message | textvariable)*)>
<!ATTLIST window
	name CDATA #REQUIRED
>
<!ELEMENT area (description, state*)>
<!ATTLIST area
	name CDATA #REQUIRED
	required (true | false) #REQUIRED
>
<!ELEMENT state (description)>
<!ATTLIST state
	name CDATA #REQUIRED
>
<!ELEMENT message (description)>
<!ATTLIST message
	name CDATA #REQUIRED
	required (true | false) #REQUIRED
>
<!ELEMENT resource (description, resource*)>
<!ATTLIST resource
	name CDATA #REQUIRED
	required (true | false) #REQUIRED
>

<!ELEMENT textvariable (description)>
<!ATTLIST textvariable
	name CDATA #REQUIRED
>

=== almost/Marvin-Jabber-Client/docs/skindef/marvin_skindef.xml
<?xml version="1.0"?>
<!DOCTYPE skindef SYSTEM "skindef.dtd">
<?xml-stylesheet type="text/xsl" href="skindef.xsl"?>
<!--POSSIBLE IDEA: Valid values for the required attrbute are: yes, no, optional and recomended-->
<!--REVISION LOG STARTED 4/July/2001:
4/July/2001 Added savepassword and autologin areas to login window and checkbox resources
23/September/2001 Changed prefs mesage to settings message in roster
22/November/2001 Added history gui sutff: history resource and history area in message window
26/November/2001 "Gateways" message in Roster window is now implemented
1/December/2001 Changed stuff around for new <state> tag
18/December/2001 Made some messages global
20/December/2001 Added "menu" message
4/Janruay/2002 Changed to reflect addition  "Text Variables" to SkinX
4/January/2002 Added $status$ and $showstate$ text variables and added showstate  area to roster window
4/January/2002 Added $recipientstatus$ and $recipientshowstate$ text variables and added recipientshowstate area to message window
6/January/2002 Added send/reply area (with send and reply states)
20/Janurary/2002 Added searchlog message
24/January/2002 Added $messageevent$ text variable to message window, added messageevent area to message window
27/February/2002 Added changepassword message
25/March/2002 Added topmost area and message to message window
21/April/2002 Added togglesounds message
-->
<skindef name="marvin">
	<description>
		This is the skin definition file for my Euphoria Jabber Client. Note that while Marvin is in heavy development this information can and probably will change...
	</description>
	<resource name="scrollbar" required="true">
		<description>
			Contains resources for the scrollbar control.
		</description>
		<resource name="up" required="true">
			<description>
				Image for the up button of the scrollbar control, should be the same size as down resource.
			</description>
		</resource>
		<resource name="down" required="true">
			<description>
				Image for the down button of the scrollbar control, should be the same size as up resource.
			</description>
		</resource>
		<resource name="background" required="true">
			<description>
				Image for the background of the scrollbar control, will be tiled.
			</description>
		</resource>
		<resource name="thumb" required="true">
			<description>
				Image for the thumb of the scrollbar.
			</description>
		</resource>
	</resource>
	<resource name="roster" required="true">
		<description>
			Contains resources for the roster.
		</description>
		<resource name="group" required="true">
			<description>
				Contains expanded and collapsed versions of the icon for group items on the roster.
			</description>
			<resource name="expanded" required="true">
				<description>
					Expanded version of the icon for group items on the roster.
				</description>
			</resource>
			<resource name="collapsed" required="true">
				<description>
					Collapsed version of the icon for group items on the roster.
				</description>
			</resource>
		</resource>
		<resource name="item" required="false">
			<description>
				Images for items (contacts) on the roster. Should be 16x16. If no images are supplied then no images will be used.
			</description>
			<resource name="offline" required="false">
				<description>
					Image for offline items (contacts) on the roster. Should be 16x16. If no image is supplied then no image will be used.
				</description>
			</resource>
			<resource name="available" required="false">
				<description>
					Image for available items (contacts) on the roster. Should be 16x16. If no image is supplied then no image will be used.
				</description>
			</resource>
			<resource name="chat" required="false">
				<description>
					Image for items (contacts) on the roster who are Free For Chat. Should be 16x16. If no image is supplied then the available image will be used.									</description>
			</resource>
			<resource name="away" required="false">
				<description>
					Image for items (contacts) on the roster who are away. Should be 16x16. If no image is supplied then the available image will be used.
				</description>
			</resource>
			<resource name="xa" required="false">
				<description>
					Image for items (contacts) on the roster who are in extended away state. Should be 16x16. If no image is supplied then the away image will be used.								</description>
			</resource>
			<resource name="dnd" required="false">
				<description>
					Image for items (contacts) on the roster who are in dnd state. Should be 16x16. If no image is supplied then the away image will be used.										</description>
			</resource>
		</resource>
	</resource>
	<resource name="systray" required="true">
		<description>
			Images for the system tray icon. Will be resized to 16x16 with 16 colors.
		</description>
		<resource name="available" required="true">
			<description>
					Image to be shown in system tray when user's state is available. Will be resized to 16x16 with 16 colors.
				</description>
		</resource>
		<resource name="chat" required="false">
			<description>
					Image to be shown in system tray when user's state is free for chat. Will be resized to 16x16 with 16 colors.
				</description>
		</resource>
		<resource name="away" required="false">
			<description>
						Image to be shown in system tray when user's state is away. Will be resized to 16x16 with 16 colors.
				</description>
		</resource>
		<resource name="xa" required="false">
			<description>
						Image to be shown in system tray when user's state is extended away. Will be resized to 16x16 with 16 colors.
				</description>
		</resource>
		<resource name="dnd" required="false">
			<description>
						Image to be shown in system tray when user's state is do not disturb. Will be resized to 16x16 with 16 colors.
				</description>
		</resource>
		<resource name="message" required="false">
			<description>
					Image to be shown in system tray when a message is waiting. Will be resized to 16x16 with 16 colors.
				</description>
		</resource>
	</resource>
	<message name="LogOff" required="true">
		<description>
			When the application recieves this message it will log the user off of the Jabber network, close the Roster window and show the Login window.
		</description>
	</message>
	<message name="Settings" required="true">
		<description>
			When the application recieves this message it will show the Settings window.
		</description>
	</message>
	<message name="SetAvailable" required="true">
		<description>
			When the application recieves this message it will set the users status to "Available".
		</description>
	</message>
	<message name="SetChat" required="true">
		<description>
			When the application recieves this message it will set the users status to "Free For Chat".
		</description>
	</message>
	<message name="SetAway" required="true">
		<description>
			When the application recieves this message it will set the users status to "Away".
		</description>
	</message>
	<message name="SetXA" required="true">
		<description>
			When the application recieves this message it will set the users status to "Extended Away".
		</description>
	</message>
	<message name="SetDND" required="true">
		<description>
			When the application recieves this message it will set the users status to "Do Not Disturb".
		</description>
	</message>
	<message name="SetCustom" required="true">
		<description>
			When the application recieves this message it will open up the Set Custom Status window.
		</description>
	</message>
	<message name="ChangeSkin" required="true">
		<description>
			When the application recieves this message it will show the Change Skin window.
		</description>
	</message>
	<message name="AddContact" required="true">
		<description>
			When the application recieves this message it will open up the add contact window.
		</description>
	</message>
	<message name="Gateways" required="true">
		<description>
			When the application recieves this message it will show the Gateway Settings window.
		</description>
	</message>
	<message name="Find" required="true">
		<description>
			When the application recieves this message it will show the Find Users window.
			NOT YET IMPLEMENTED
		</description>
	</message>
	<message name="Menu" required="true">
		<description>
			This message will display a popup menu containing all the functions required for the current window. The idea here is that if new features are added old skins will still be usable...
		</description>
	</message>
	<message name="ChangePassword" required="false">
		<description>
			This message will bring up a dialog that allows the user to change their password.
		</description>
	</message>
	<message name="ToggleSounds" required="false">
		<description>
			Will toggle sounds on or off.
		</description>
	</message>
	<window name="roster">
		<description>
			This is the main window of the client, it shows a list of all contacts on the users roster and alows the user to send messages to them.
		</description>
		<area name="roster" required="true">
			<description>
				The main part of the roster control will be placed in this area.
			</description>
		</area>
		<area name="rosterscroll" required="true">
			<description>
				The scrollbar used to scroll the roster list will be places in this area.
			</description>
		</area>
		<area name="topmost" required="false">
			<description>
				This area's state is changed to reflect whether the roster is currently a topmost window (hovers over other windows). I sugest that this area send the "topmost" message on left click, this will make it work like a toggle.
			</description>
			<state name="on">
				<description>
					The image(s)  to display when the roster is a topmost window
				</description>
			</state>
			<state name="off">
				<description>
					The image(s)  to display when the roster is not a topmost window
				</description>
			</state>
		</area>
		<area name="showstate" required="false">
